hack/update-expected.sh

diff --git a/tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script b/tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
--- a/tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
+++ b/tests/integration/update_cluster/ha_gce/data/google_compute_instance_template_master-us-test1-b-ha-gce-example-com_metadata_startup-script
@@ -26,13 +26,20 @@ function ensure-install-dir() {
   cd ${INSTALL_DIR}
 }
 
-# Retry a download until we get it. args: name, sha, url1, url2...
+# Retry a download until we get it. args: name, sha, urls
 download-or-bust() {
   local -r file="$1"
   local -r hash="$2"
-  shift 2
+  local -r urls=( $(split-commas "$3") )
 
-  urls=( $* )
+  if [[ -f "${file}" ]]; then
+	if ! validate-hash "${file}" "${hash}"; then
+	  rm -f "${file}"
+	else
+	  return
+	fi
+  fi
+
   while true; do
     for url in "${urls[@]}"; do
       commands=(
@@ -78,15 +85,6 @@ function split-commas() {
   echo $1 | tr "," "\n"
 }
 
-function try-download-release() {
-  local -r nodeup_urls=( $(split-commas "${NODEUP_URL}") )
-
-  echo "Downloading nodeup (${nodeup_urls[@]})"
-  download-or-bust nodeup "${NODEUP_HASH}" "${nodeup_urls[@]}"
-
-  chmod +x nodeup
-}
-
 function download-release() {
   case "$(uname -m)" in
   x86_64*|i?86_64*|amd64*)
@@ -104,7 +102,9 @@ function download-release() {
   esac
 
   cd ${INSTALL_DIR}/bin
-  try-download-release
+  download-or-bust nodeup "${NODEUP_HASH}" "${NODEUP_URL}"
+
+  chmod +x nodeup
 
   echo "Running nodeup"
   # We can't run in the foreground because of https://github.com/docker/docker/issues/23793
