Run hack/update-expected.sh

diff --git a/tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/apiservernodes/cloudformation.json.extracted.yaml
@@ -118,7 +118,10 @@ Resources.AWSEC2LaunchTemplateapiserverapiserversminimalexamplecom.Properties.La
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -294,7 +297,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersminimalexamplecom.Properties.
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -565,7 +571,10 @@ Resources.AWSEC2LaunchTemplatenodesminimalexamplecom.Properties.LaunchTemplateDa
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/complex/cloudformation.json.extracted.yaml
@@ -127,7 +127,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amasterscomplexexamplecom.Properties.
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -406,7 +409,10 @@ Resources.AWSEC2LaunchTemplatenodescomplexexamplecom.Properties.LaunchTemplateDa
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/docker-custom/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/docker-custom/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/docker-custom/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/docker-custom/cloudformation.json.extracted.yaml
@@ -118,7 +118,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersdockerexamplecom.Properties.L
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -387,7 +390,10 @@ Resources.AWSEC2LaunchTemplatenodesdockerexamplecom.Properties.LaunchTemplateDat
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/minimal-ipv6/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/minimal-ipv6/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/minimal-ipv6/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/minimal-ipv6/cloudformation.json.extracted.yaml
@@ -118,7 +118,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersminimalipv6examplecom.Propert
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -391,7 +394,10 @@ Resources.AWSEC2LaunchTemplatenodesminimalipv6examplecom.Properties.LaunchTempla
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/minimal-longclustername/cloudformation.json.extracted.yaml
@@ -119,7 +119,10 @@
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -371,7 +374,10 @@
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/mixed_instances_spot/cloudformation.json.extracted.yaml
@@ -118,7 +118,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersmixedinstancesexamplecom.Prop
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -371,7 +374,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1bmastersmixedinstancesexamplecom.Prop
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -624,7 +630,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1cmastersmixedinstancesexamplecom.Prop
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -877,7 +886,10 @@ Resources.AWSEC2LaunchTemplatenodesmixedinstancesexamplecom.Properties.LaunchTem
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/nth_sqs_resources/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/nth_sqs_resources/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/nth_sqs_resources/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/nth_sqs_resources/cloudformation.json.extracted.yaml
@@ -119,7 +119,10 @@
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -368,7 +371,10 @@ Resources.AWSEC2LaunchTemplatenodesnthsqsresourceslongclusternameexamplecom.Prop
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/private-shared-ip/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/private-shared-ip/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/private-shared-ip/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/private-shared-ip/cloudformation.json.extracted.yaml
@@ -119,7 +119,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersprivatesharedipexamplecom.Pro
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -372,7 +375,10 @@ Resources.AWSEC2LaunchTemplatenodesprivatesharedipexamplecom.Properties.LaunchTe
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/privatecalico/cloudformation.json.extracted.yaml
@@ -119,7 +119,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersprivatecalicoexamplecom.Prope
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -388,7 +391,10 @@ Resources.AWSEC2LaunchTemplatenodesprivatecalicoexamplecom.Properties.LaunchTemp
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
diff --git a/tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/privateciliumadvanced/cloudformation.json.extracted.yaml
@@ -119,7 +119,10 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersprivateciliumadvancedexamplec
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
@@ -375,7 +378,10 @@ Resources.AWSEC2LaunchTemplatenodesprivateciliumadvancedexamplecom.Properties.La
 
   ####################################################################################
 
-  /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  if [[ ! -s /etc/machine-id ]]; then
+    echo "Generating machine-id"
+    /bin/systemd-machine-id-setup || echo "failed to set up ensure machine-id configured"
+  fi
 
   echo "== nodeup node config starting =="
   ensure-install-dir
