Update expected test for new script

diff --git a/tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/additional_user-data/cloudformation.json.extracted.yaml
@@ -95,9 +95,9 @@ Resources.AWSAutoScalingLaunchConfigurationmasterustest1amastersadditionaluserda
     local -r expected="$2"
     local actual
 
-    actual=$(sha1sum ${file} | awk '{ print $1 }') || true
+    actual=$(sha256sum ${file} | awk '{ print $1 }') || true
     if [[ "${actual}" != "${expected}" ]]; then
-      echo "== ${file} corrupted, sha1 ${actual} doesn't match expected ${expected} =="
+      echo "== ${file} corrupted, hash ${actual} doesn't match expected ${expected} =="
       return 1
     fi
   }
@@ -115,9 +115,9 @@ Resources.AWSAutoScalingLaunchConfigurationmasterustest1amastersadditionaluserda
       local -r nodeup_hash="${NODEUP_HASH}"
     else
     # TODO: Remove?
-      echo "Downloading sha1 (not found in env)"
-      download-or-bust nodeup.sha1 "" "${nodeup_urls[@]/%/.sha1}"
-      local -r nodeup_hash=$(cat nodeup.sha1)
+      echo "Downloading sha256 (not found in env)"
+      download-or-bust nodeup.sha256 "" "${nodeup_urls[@]/%/.sha256}"
+      local -r nodeup_hash=$(cat nodeup.sha256)
     fi
 
     echo "Downloading nodeup (${nodeup_urls[@]})"
@@ -389,9 +389,9 @@ Resources.AWSAutoScalingLaunchConfigurationnodesadditionaluserdataexamplecom.Pro
     local -r expected="$2"
     local actual
 
-    actual=$(sha1sum ${file} | awk '{ print $1 }') || true
+    actual=$(sha256sum ${file} | awk '{ print $1 }') || true
     if [[ "${actual}" != "${expected}" ]]; then
-      echo "== ${file} corrupted, sha1 ${actual} doesn't match expected ${expected} =="
+      echo "== ${file} corrupted, hash ${actual} doesn't match expected ${expected} =="
       return 1
     fi
   }
@@ -409,9 +409,9 @@ Resources.AWSAutoScalingLaunchConfigurationnodesadditionaluserdataexamplecom.Pro
       local -r nodeup_hash="${NODEUP_HASH}"
     else
     # TODO: Remove?
-      echo "Downloading sha1 (not found in env)"
-      download-or-bust nodeup.sha1 "" "${nodeup_urls[@]/%/.sha1}"
-      local -r nodeup_hash=$(cat nodeup.sha1)
+      echo "Downloading sha256 (not found in env)"
+      download-or-bust nodeup.sha256 "" "${nodeup_urls[@]/%/.sha256}"
+      local -r nodeup_hash=$(cat nodeup.sha256)
     fi
 
     echo "Downloading nodeup (${nodeup_urls[@]})"
