Update kubernetes to master branch

diff --git a/vendor/k8s.io/kubernetes/hooks/pre-commit b/vendor/k8s.io/kubernetes/hooks/pre-commit
--- a/vendor/k8s.io/kubernetes/hooks/pre-commit
+++ b/vendor/k8s.io/kubernetes/hooks/pre-commit
@@ -62,6 +62,18 @@ else
 fi
 echo "${reset}"
 
+echo -ne "Checking for package aliases... "
+if ! hack/verify-pkg-names.sh > /dev/null; then
+  echo "${red}ERROR!"
+  echo "Some package aliases break go conventions. To fix these errors, "
+  echo "do not use capitalized or underlined characters in pkg aliases. "
+  echo "Refer to https://blog.golang.org/package-names for more info."
+  exit_code=1
+else
+  echo "${green}OK"
+fi
+echo "${reset}"
+
 echo -ne "Checking for files that need boilerplate... "
 files=($(git diff --cached --name-only --diff-filter ACM))
 # We always make sure there is one file in the files list. Some tools check
@@ -116,18 +128,6 @@ if [[ "${#files_need_description[@]}" -ne 0 ]]; then
   for file in "${files_need_description[@]}"; do
     echo "  ${file}"
   done
-  exit_code=1
-else
-  echo "${green}OK"
-fi
-echo "${reset}"
-
-echo -ne "Checking for docs that need updating... "
-if ! hack/verify-munge-docs.sh > /dev/null; then
-  echo "${red}ERROR!"
-  echo "Some docs are out of sync between CLI and markdown."
-  echo "To regenerate docs, run:"
-  echo "  hack/update-munge-docs.sh"
   exit_code=1
 else
   echo "${green}OK"
