Convert all indents to spaces in node bootstrap script

diff --git a/tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml b/tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
--- a/tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
+++ b/tests/integration/update_cluster/minimal-cloudformation/cloudformation.json.extracted.yaml
@@ -28,13 +28,20 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersminimalexamplecom.Properties.
     cd ${INSTALL_DIR}
   }
 
-  # Retry a download until we get it. args: name, sha, url1, url2...
+  # Retry a download until we get it. args: name, sha, urls
   download-or-bust() {
     local -r file="$1"
     local -r hash="$2"
-    shift 2
+    local -r urls=( $(split-commas "$3") )
 
-    urls=( $* )
+    if [[ -f "${file}" ]]; then
+      if ! validate-hash "${file}" "${hash}"; then
+        rm -f "${file}"
+      else
+        return
+      fi
+    fi
+
     while true; do
       for url in "${urls[@]}"; do
         commands=(
@@ -80,15 +87,6 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersminimalexamplecom.Properties.
     echo $1 | tr "," "\n"
   }
 
-  function try-download-release() {
-    local -r nodeup_urls=( $(split-commas "${NODEUP_URL}") )
-
-    echo "Downloading nodeup (${nodeup_urls[@]})"
-    download-or-bust nodeup "${NODEUP_HASH}" "${nodeup_urls[@]}"
-
-    chmod +x nodeup
-  }
-
   function download-release() {
     case "$(uname -m)" in
     x86_64*|i?86_64*|amd64*)
@@ -106,7 +104,9 @@ Resources.AWSEC2LaunchTemplatemasterustest1amastersminimalexamplecom.Properties.
     esac
 
     cd ${INSTALL_DIR}/bin
-    try-download-release
+    download-or-bust nodeup "${NODEUP_HASH}" "${NODEUP_URL}"
+
+    chmod +x nodeup
 
     echo "Running nodeup"
     # We can't run in the foreground because of https://github.com/docker/docker/issues/23793
@@ -343,13 +343,20 @@ Resources.AWSEC2LaunchTemplatenodesminimalexamplecom.Properties.LaunchTemplateDa
     cd ${INSTALL_DIR}
   }
 
-  # Retry a download until we get it. args: name, sha, url1, url2...
+  # Retry a download until we get it. args: name, sha, urls
   download-or-bust() {
     local -r file="$1"
     local -r hash="$2"
-    shift 2
+    local -r urls=( $(split-commas "$3") )
 
-    urls=( $* )
+    if [[ -f "${file}" ]]; then
+      if ! validate-hash "${file}" "${hash}"; then
+        rm -f "${file}"
+      else
+        return
+      fi
+    fi
+
     while true; do
       for url in "${urls[@]}"; do
         commands=(
@@ -395,15 +402,6 @@ Resources.AWSEC2LaunchTemplatenodesminimalexamplecom.Properties.LaunchTemplateDa
     echo $1 | tr "," "\n"
   }
 
-  function try-download-release() {
-    local -r nodeup_urls=( $(split-commas "${NODEUP_URL}") )
-
-    echo "Downloading nodeup (${nodeup_urls[@]})"
-    download-or-bust nodeup "${NODEUP_HASH}" "${nodeup_urls[@]}"
-
-    chmod +x nodeup
-  }
-
   function download-release() {
     case "$(uname -m)" in
     x86_64*|i?86_64*|amd64*)
@@ -421,7 +419,9 @@ Resources.AWSEC2LaunchTemplatenodesminimalexamplecom.Properties.LaunchTemplateDa
     esac
 
     cd ${INSTALL_DIR}/bin
-    try-download-release
+    download-or-bust nodeup "${NODEUP_HASH}" "${NODEUP_URL}"
+
+    chmod +x nodeup
 
     echo "Running nodeup"
     # We can't run in the foreground because of https://github.com/docker/docker/issues/23793
